backend:
  name: git-gateway
  repo: developerstrategy/weblabel
  #repo: ali-baker/huss-gatsby
media_folder: "static/assets/images"
public_folder: "/assets/images"
media_folder_relative: true

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "Homepage"
        file: "src/markdownPages/homepage.md"
        fields:
          - { label: Slider Titulo, name: title, widget: string }
          - { label: Slider SubTitulo, name: subtitle, widget: string }
          - {
              label: "Slider Imagen",
              name: "thumbnail",
              widget: "image",
              default: "",
            }
          - { label: Incino Titulo, name: incino_title, widget: string }
          - { label: Incino Description Titulo, name: incino_description_title, widget: string }
          - { label: Incino Description, name: incino_description, widget: markdown }
          - {
              label: "Incino Imagen",
              name: "incino_thumbnail",
              widget: "image",
              default: "",
            }
          - { label: Proyecto Subtitulo, name: proyecto_subtitulo, widget: string }
          - { label: Proyecto Titulo, name: proyecto_titulo, widget: string }

          # - { label: Second Section Title, name: title2, widget: string }
          # - { label: Second Section SubTitle, name: subtitle2, widget: text }
          # - { label: Contact Section Title, name: contacttitle, widget: string }
          # - { label: E-mail, name: email, widget: string }
          # - { label: Contact, name: contact, widget: string }
          - label: "Table data"
            name: "listitems"
            widget: "list"
            fields:
              - { label: "Proyecto Imagen", name: "proyecto_imagen", widget: "image" }
          - { label: Bloque Titulo, name: bloque_titulo, widget: string }
          - { label: Bloque Description, name: bloque_description, widget: markdown }
          - label: "Table data"
            name: "beneficos"
            widget: "list"
            fields:
              - { label: "Proyecto Imagen", name: "proyecto_imagen", widget: "image", optional: true, required: false}
              - { label: Beneficios SubTitulo, name: beneficios_subtitulo, widget: string }
              - { label: Beneficios Titulo, name: beneficios_titulo, widget: string }
              - { label: Beneficios Description, name: beneficios_description, widget: markdown }