backend:
  name: github
  repo: developerstrategy/weblabel
  #repo: ali-baker/huss-gatsby
media_folder: "static/assets/images"
public_folder: "static/assets/images"
media_folder_relative: true

collections:
  - name: education
    label: Education
    folder: education
    create: true
    fields:
      - { name: blogtitle, label: Blog Title }
      - { name: path, label: Path (post url) }
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: Author, widget: string }
      - {
          label: "Education Page",
          name: "educationpage",
          widget: "hidden",
          default: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          default: "wholesale.png",
        }
      - { name: body, label: Body, widget: markdown }
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: blogtitle, label: Blog Title }
      - { name: path, label: Path (post url) }
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: Author, widget: string }
      - {
          label: "Blog Page",
          name: "blogpage",
          widget: "hidden",
          default: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          default: "wholesale.png",
        }
      - { name: body, label: Body, widget: markdown }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Wholesale"
        name: "wholesale"
        file: "src/markdown-pages/wholesale.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Second Section Title, name: title2, widget: string }
          - { label: Second Section SubTitle, name: subtitle2, widget: text }
          - { label: Contact Section Title, name: contacttitle, widget: string }
          - { label: E-mail, name: email, widget: string }
          - { label: Contact, name: contact, widget: string }
          - label: "Table data"
            name: "listitems"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
      - label: "Footer"
        name: "Footer"
        file: "src/markdown-pages/footer.md"
        fields:
          - { label: Office Floor, name: office, widget: string }
          - {
              label: Office Street Address,
              name: officestreet,
              widget: markdown,
            }
          - { label: Office City, name: officecity, widget: string }
          - { label: Postal GPO, name: postalgpo, widget: string }
          - { label: Postal Address City, name: postalcity, widget: string }
          - { label: E-mail, name: email, widget: string }
          - { label: Contact, name: number, widget: string }
          - { label: First Footer Description, name: footerdesc1, widget: text }
          - {
              label: Second Footer Description,
              name: footerdesc2,
              widget: text,
            }
          - { label: Third Footer Description, name: footerdesc3, widget: text }
          - {
              label: Fourth Footer Description,
              name: footerdesc4,
              widget: text,
            }

      - label: "About Page"
        name: "About Page"
        file: "src/markdown-pages/about.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Button Text, name: buttontext, widget: string }
          - { label: Button Email, name: buttonemail, widget: string }
          - { label: Title Section 1, name: careertitle, widget: string }
          - {
              label: Description Section 1,
              name: careerdescription,
              widget: string,
            }
          - { label: Title Section 2, name: lifetitle, widget: string }
          - {
              label: Description Section 2,
              name: lifedescription,
              widget: string,
            }
      - label: "Financial Services Guide"
        name: "Financial Services Guide"
        file: "src/markdown-pages/financial-services-guide.md"
        fields:
          - { label: Policy, name: policy, widget: markdown }
      - label: "Complaints Policy"
        name: "Complaints Policy"
        file: "src/markdown-pages/complaints-policy.md"
        fields:
          - { label: Policy, name: policy, widget: markdown }
      - label: "Privacy Page"
        name: "Privacy Page"
        file: "src/markdown-pages/privacy-policy.md"
        fields:
          - { label: Policy, name: policy, widget: markdown }
      - label: "Privacy Policy Credit"
        name: "Privacy Policy Credit"
        file: "src/markdown-pages/privacy-policy-credit.md"
        fields:
          - { label: Policy, name: policy, widget: markdown }
      - label: "CPD Page"
        name: "CPD Page"
        file: "src/markdown-pages/continuing-professional-development-policy.md"
        fields:
          - { label: Policy, name: policy, widget: markdown }

      - label: "How we do it"
        name: "How we do it"
        file: "src/markdown-pages/advisory.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: FAQ1, name: FAQ1, widget: string }
          - { label: FAQ1 Answer, name: answer1, widget: markdown }
          - { label: FAQ2, name: FAQ2, widget: string }
          - { label: FAQ2 Answer, name: answer2, widget: markdown }
          - { label: FAQ3, name: FAQ3, widget: string }
          - { label: FAQ3 Answer, name: answer3, widget: markdown }
          - { label: FAQ4, name: FAQ4, widget: string }
          - { label: FAQ4 Answer, name: answer4, widget: markdown }
          - { label: Contact Title, name: contacttitle, widget: string }
          - { label: Contact Desc, name: contactdesc, widget: text }
      - label: "What we do"
        name: "What we do"
        file: "src/markdown-pages/help.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - {
              label: "Featured Image",
              name: "mainImage",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Third Help Title, name: helptitle3, widget: string }
          - label: "Help data 3"
            name: "helplist3"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fourth Help Title, name: helptitle4, widget: string }
          - label: "Help data 4"
            name: "helplist4"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fifth Help Title, name: helptitle5, widget: string }
          - label: "Help data 5"
            name: "helplist5"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Sixth Help Title, name: helptitle6, widget: string }
          - label: "Help data 6"
            name: "helplist6"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
          - { label: Help Main, name: helpmain, widget: string }
          - { label: Help Section 1, name: help1, widget: string }
          - { label: Help Desc 1, name: helpdesc1, widget: text }
          - { label: Help Section 2, name: help2, widget: string }
          - { label: Help Desc 2, name: helpdesc2, widget: text }
          - { label: Help Title New, name: helpnewtitle, widget: string }
          - { label: Help Desc New, name: helpnewdesc, widget: text }
          - { label: Help Section 3, name: help3, widget: string }
          - { label: Help Desc 3, name: helpdesc3, widget: text }
          - { label: Help Section 4, name: help4, widget: string }
          - { label: Help Desc 4, name: helpdesc4, widget: text }
          - { label: Help Title Last, name: helplasttitle, widget: string }
          - { label: Help Desc Last, name: helplasdesc, widget: text }

          - { label: Contact Title, name: contacttitle, widget: string }
          - { label: Contact Desc, name: contactdesc, widget: string }

      - label: "Service Packages"
        name: "Service Packages"
        file: "src/markdown-pages/service-packages.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Packages Title, name: packagestitle, widget: string }
          - {
              label: Packages Description,
              name: packagesdescription,
              widget: text,
            }
          - { label: First Package, name: firstpackage, widget: string }
          - {
              label: First Package Price,
              name: firstpackageprice,
              widget: string,
            }
          - {
              label: First Package Description,
              name: firstpackagedescription,
              widget: string,
            }
          - label: "First Package Benefits"
            name: "benefits1"
            widget: "list"
            fields:
              - { label: "Benefits", name: "benefit", widget: "markdown" }
          - { label: Second Package, name: secondpackage, widget: string }
          - {
              label: Second Package Price,
              name: secondpackageprice,
              widget: string,
            }
          - {
              label: Second Package Description,
              name: secondpackagedescription,
              widget: string,
            }
          - label: "Second Package Benefits"
            name: "benefits2"
            widget: "list"
            fields:
              - { label: "Benefits", name: "benefit", widget: "markdown" }
          - { label: Third Package, name: thirdpackage, widget: string }
          - {
              label: Third Package Price,
              name: thirdpackageprice,
              widget: string,
            }
          - {
              label: Third Package Description,
              name: thirdpackagedescription,
              widget: string,
            }
          - label: "First Package Benefits"
            name: "benefits3"
            widget: "list"
            fields:
              - { label: "Benefits", name: "benefit", widget: "markdown" }
          - { label: Fourth Package, name: fourthpackage, widget: string }
          - {
              label: Fourth Package Price,
              name: fourthpackageprice,
              widget: string,
            }
          - {
              label: Fourth Package Description,
              name: fourthpackagedescription,
              widget: string,
            }
          - label: "Fourth Package Benefits"
            name: "benefits4"
            widget: "list"
            fields:
              - { label: "Benefits", name: "benefit", widget: "markdown" }
          - {
              label: Wealth Portal Title,
              name: wealthportaltitle,
              widget: string,
            }
          - {
              label: Wealth Portal Description,
              name: wealthportaldescription,
              widget: text,
            }
          - { label: Wealth Portal Video Link, name: videolink, widget: string }
          - { label: Service Title, name: servicestitle, widget: string }
          - {
              label: Service Description,
              name: servicesdescription,
              widget: text,
            }
          - {
              label: First Service Title,
              name: firstservicestitle,
              widget: string,
            }
          - {
              label: First Service Description,
              name: firstservicesdescription,
              widget: text,
            }
          - {
              label: Second Service Title,
              name: secondservicestitle,
              widget: string,
            }
          - {
              label: Second Service Description,
              name: secondservicesdescription,
              widget: text,
            }
          - {
              label: Third Service Title,
              name: thirdservicestitle,
              widget: string,
            }
          - {
              label: Third Service Description,
              name: thirdservicesdescription,
              widget: text,
            }
          - {
              label: Fourth Service Title,
              name: fourthservicestitle,
              widget: string,
            }
          - {
              label: Fourth Service Description,
              name: fourthservicesdescription,
              widget: text,
            }
          - {
              label: Fifth Service Title,
              name: fifthservicestitle,
              widget: string,
            }
          - {
              label: Fifth Service Description,
              name: fifthservicesdescription,
              widget: text,
            }
          - {
              label: Sixth Service Title,
              name: sixthservicestitle,
              widget: string,
            }
          - {
              label: Sixth Service Description,
              name: sixthservicesdescription,
              widget: text,
            }

          - label: "Help data 3"
            name: "helplist3"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fourth Help Title, name: helptitle4, widget: string }
          - label: "Help data 4"
            name: "helplist4"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Fifth Help Title, name: helptitle5, widget: string }
          - label: "Help data 5"
            name: "helplist5"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
          - { label: Sixth Help Title, name: helptitle6, widget: string }
          - label: "Help data 6"
            name: "helplist6"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
          - { label: Help Main, name: helpmain, widget: string, optional: true }
          - { label: Help Section 1, name: help1, widget: string }
          - { label: Help Desc 1, name: helpdesc1, widget: text }
          - { label: Help Section 2, name: help2, widget: string }
          - { label: Help Desc 2, name: helpdesc2, widget: text }
          - { label: Help Title New, name: helpnewtitle, widget: string }
          - { label: Help Desc New, name: helpnewdesc, widget: text }
          - { label: Help Section 3, name: help3, widget: string }
      - label: "Index Page"
        name: "Index Page"
        file: "src/markdown-pages/index.md"
        fields:
          - { label: Main Title, name: title, widget: string }
          - { label: SubTitle, name: subtitle, widget: text }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Second Section Main Title, name: title2, widget: string }
          - { label: First Description, name: desc1, widget: text }
          - { label: Second Description, name: desc2, widget: text }
          - { label: Third Description, name: desc3, widget: text }
          - { label: Services, name: services, widget: text }
          - { label: Main Service Title, name: servicestitle, widget: text }
          - { label: First Service, name: service1, widget: text }
          - { label: Second Service, name: service2, widget: text }
          - { label: Third Service, name: service3, widget: text }
          - { label: Fourth Service, name: service4, widget: text }
          - { label: Fifth Service, name: service5, widget: text }
          - { label: Sixth Service, name: service6, widget: text }
          - { label: Advisory Title, name: advisorytitle, widget: text }
          - { label: Advisory Description, name: advisorydesc, widget: text }
          - label: "Customer Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Review", name: "review", widget: "text" }
              - { label: "Picture", name: "pic", widget: "image" }
              - { label: "Customer name", name: "name", widget: "string" }
          - { label: Contact Title, name: contacttitle, widget: string }
          - { label: Contact Desc, name: contactdesc, widget: string }
