backend:
  name: github
  repo: developerstrategy/weblabel
  #repo: ali-baker/huss-gatsby
media_folder: "static/assets/images"
public_folder: "/assets/images"
media_folder_relative: true

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "Homepage"
        file: "src/markdownPages/homepage.md"
        fields:
          - { label: Slider Titulo, name: title, widget: string }
          - { label: Slider SubTitulo, name: subtitle, widget: string }
          - {
              label: "Slider Imagen",
              name: "thumbnail",
              widget: "image",
              default: "",
            }
          # - { label: Second Section Title, name: title2, widget: string }
          # - { label: Second Section SubTitle, name: subtitle2, widget: text }
          # - { label: Contact Section Title, name: contacttitle, widget: string }
          # - { label: E-mail, name: email, widget: string }
          # - { label: Contact, name: contact, widget: string }
          # - label: "Table data"
          #   name: "listitems"
          #   widget: "list"
          #   fields:
          #     - { label: "Title", name: "title", widget: "text" }
      