backend:
  name: github
  repo: developerstrategy/weblabel
  #repo: ali-baker/huss-gatsby
media_folder: "static/assets/images"
public_folder: "static/assets/images"
media_folder_relative: true

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Wholesale"
        name: "wholesale"
        file: "src/markdown-pages/wholesale.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - {
              label: "Featured Image",
              name: "thumbnail",
              widget: "image",
              default: "wholesale.png",
            }
          - { label: Second Section Title, name: title2, widget: string }
          - { label: Second Section SubTitle, name: subtitle2, widget: text }
          - { label: Contact Section Title, name: contacttitle, widget: string }
          - { label: E-mail, name: email, widget: string }
          - { label: Contact, name: contact, widget: string }
          - label: "Table data"
            name: "listitems"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "text" }
      